# Generated by Django 4.2.2 on 2023-11-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_product_games'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Product',
        ),
    ]
